[package]
name = "easyjack"
version = "0.0.1"
authors = ["David Zmick <dpzmick@gmail.com>"]
description = "Easy, rusty, bindings for the jack api"
license = "MIT"
build = "build.rs"

[dependencies]
bitflags = "0.7"
getopts = "0.2.4"
jack-sys = "0.1.0"
libc = "0.2"
nix = "0.7.0"
num = "0.1"
